services:
  - type: web
    name: projectUserLog
    env: docker
    repo: https://github.com/your-username/projectUserLog
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: projectuserlog_db
      - key: DB_USER
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password
