version: "3.8"
services:
  # Your PHP app
  app:
    build: .
    ports:
      - "10000:10000" # Expose PHP app
    depends_on:
      - mysql # Wait for MySQL to start
    environment:
      DB_HOST: "${DB_HOST}" # Docker network magic!
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"

  # MySQL container
  mysql:
    image: mysql:8.0 # Official MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - mysql_data:/var/lib/mysql # Persist data

volumes:
  mysql_data: # Named volume to save data

