name: PHP Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, pdo, pdo_mysql
        coverage: none

    - name: Validate PHP files
      run: |
        echo "Running PHP lint check"
        find . -name "*.php" -print0 | xargs -0 -n1 php -l

# this workflow is for automatically setting up the php server on github
